//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refactoring.Conway {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Refactoring.Conway.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Completed! Press any key to exit..
        /// </summary>
        internal static string AppExitMessage {
            get {
                return ResourceManager.GetString("AppExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the height of the board?.
        /// </summary>
        internal static string BoardHeightPrompt {
            get {
                return ResourceManager.GetString("BoardHeightPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the width of the board?.
        /// </summary>
        internal static string BoardWidthPrompt {
            get {
                return ResourceManager.GetString("BoardWidthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Enter for default of {0}).
        /// </summary>
        internal static string DefaultValueLabel {
            get {
                return ResourceManager.GetString("DefaultValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess that&apos;s the end of our little society..
        /// </summary>
        internal static string EndGameMessage {
            get {
                return ResourceManager.GetString("EndGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many generations does the board run for?.
        /// </summary>
        internal static string GameGenerationCountPrompt {
            get {
                return ResourceManager.GetString("GameGenerationCountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        internal static string GenerationLabel {
            get {
                return ResourceManager.GetString("GenerationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020 has struck!.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user cancelled!.
        /// </summary>
        internal static string UserCancelled {
            get {
                return ResourceManager.GetString("UserCancelled", resourceCulture);
            }
        }
    }
}
